version: '3'

services:
  user-management:
    container_name: user-management
    command: sh -c "alembic upgrade head && uvicorn --factory src.main:create_app --host 0.0.0.0 --port 8000 --reload"
    build:
      context: ./user_management
    volumes:
      - ./user_management:/app
    ports:
      - "8000:8000"
    networks:
      - innotter
    depends_on:
      - db
      - redis
      - localstack
  db:
    image: postgres:15
    ports:
      - "5434:5432"
    env_file:
      - user_management/.env
    networks:
      - innotter
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  db_test:
    image: postgres:15
    env_file:
      - user_management/.env
    environment:
      POSTGRES_DB: test_db
    networks:
      - innotter
    ports:
      - "5433:5432"
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    networks:
      - innotter
    volumes:
      - redis_data:/data
  localstack:
    container_name: localstack
    image: localstack/localstack:2.3
    hostname: localstack
    env_file:
      - user_management/.env
    ports:
      - "4566:4566"
      - 8080:8080
    environment:
      - SERVICES=s3,ses
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
    networks:
      - innotter
    volumes:
      - localstack-data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./user_management/localstack-script.sh:/etc/localstack/init/ready.d/script.sh

volumes:
  postgres_data:
  redis_data:
  localstack-data:
networks:
  innotter:
    external: true
