version: '3'

services:
  user-management:
    container_name: user-management
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    build:
      context: ./user_management
    volumes:
      - ./user_management:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - user_management/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
