version: '3'

services:
  user-management:
    container_name: user-management
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    build:
      context: ./user_management
    volumes:
      - .:/app/app
    ports:
      - "8000:8000"
