"""is_blocked default False

Revision ID: 099507c56e1a
Revises: e7222cd6ac0e
Create Date: 2023-10-15 11:15:57.160541

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "099507c56e1a"
down_revision: Union[str, None] = "e7222cd6ac0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
