"""String -> Text

Revision ID: 15f7f0f7fa15
Revises: 84660e6af245
Create Date: 2023-10-10 10:03:19.209355

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15f7f0f7fa15"
down_revision: Union[str, None] = "84660e6af245"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "group",
        "name",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "name",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "surname",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "username",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "phone_number",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "s3_path",
        existing_type=sa.VARCHAR(length=2083),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "s3_path",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=2083),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "phone_number",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "email",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "username",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=250),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "surname",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=250),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=250),
        existing_nullable=False,
    )
    op.alter_column(
        "group",
        "name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
