"""Add nullable

Revision ID: 2d6870df9d78
Revises: 9f2b2985a96d
Create Date: 2023-10-13 10:14:55.553830

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d6870df9d78"
down_revision: Union[str, None] = "9f2b2985a96d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "surname", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "hashed_password", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "phone_number", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "group_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("user", "s3_path", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "s3_path", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "group_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("user", "phone_number", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "hashed_password", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "surname", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "name", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
