"""Email is nullable

Revision ID: e7222cd6ac0e
Revises: 2604bb929dc2
Create Date: 2023-10-13 13:22:24.316240

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7222cd6ac0e"
down_revision: Union[str, None] = "2604bb929dc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
