name: main
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create dotenv files
        run: |
          echo "${{ secrets.ENV_FILE }}" > user_management/.env
      - name: Start Docker daemon
        run: |
          sudo systemctl start docker
      - name: Build and Run Docker containers
        run: |
          docker-compose up -d
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pre-commit
        run: |
          python -m pip install pre-commit
      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files --show-diff-on-failure
  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          docker-compose exec -T user-management python -m pytest
